-- MiniGram: Supabase 초기 설정
-- Supabase Dashboard > SQL Editor에서 한 번 실행하세요.

-- 1) 유저 공개 프로필
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null check (char_length(username) between 2 and 30),
  created_at timestamptz not null default now()
);

-- 닉네임 중복을 허용하고 싶으면 아래 unique index를 만들지 마세요.
-- 현재 예제는 "개인 유저마다 닉네임 구분"을 위해 중복을 막습니다.
create unique index if not exists profiles_username_lower_unique
on public.profiles (lower(username));

-- 2) 게시글
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 500),
  created_at timestamptz not null default now()
);

create index if not exists posts_created_at_idx
on public.posts (created_at desc);

create index if not exists posts_user_id_idx
on public.posts (user_id);

-- 3) 회원가입 시 auth.users의 metadata(username)를 public.profiles에 자동 생성
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, username)
  values (
    new.id,
    coalesce(
      nullif(trim(new.raw_user_meta_data ->> 'username'), ''),
      'user_' || substr(new.id::text, 1, 8)
    )
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 4) RLS 활성화
alter table public.profiles enable row level security;
alter table public.posts enable row level security;

-- 기존 정책이 있다면 재실행 편의를 위해 삭제
drop policy if exists "Profiles are viewable by everyone" on public.profiles;
drop policy if exists "Users can update own profile" on public.profiles;

drop policy if exists "Posts are viewable by everyone" on public.posts;
drop policy if exists "Authenticated users can create own posts" on public.posts;
drop policy if exists "Users can update own posts" on public.posts;
drop policy if exists "Users can delete own posts" on public.posts;

-- 프로필은 피드 작성자 표시를 위해 누구나 조회 가능
create policy "Profiles are viewable by everyone"
on public.profiles
for select
to anon, authenticated
using (true);

-- 본인 프로필만 수정 가능
create policy "Users can update own profile"
on public.profiles
for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

-- 게시글 조회는 누구나 가능
create policy "Posts are viewable by everyone"
on public.posts
for select
to anon, authenticated
using (true);

-- 로그인한 사용자는 자기 user_id로만 게시 가능
create policy "Authenticated users can create own posts"
on public.posts
for insert
to authenticated
with check ((select auth.uid()) = user_id);

-- 본인 글만 수정 가능
create policy "Users can update own posts"
on public.posts
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

-- 본인 글만 삭제 가능
create policy "Users can delete own posts"
on public.posts
for delete
to authenticated
using ((select auth.uid()) = user_id);
